### ISSUE TITLE
Setup lets encrypt auto-renew

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/snapCloud#80]
This shouldn't be too difficult.

We should have an auto-renew script in bin/.

It should:
* assert certbot is installed
* run certbot renew
* copy the cert files to the proper location
* restart nginx

I should do this before August 19!

**Comment by cycomachead** [comment]
OK, this should be working on the production server. I did things in a somewhat sad way, but that are workable.

The certbot sets up a cronjob automatically (/etc/cron.d/certbot) upon install so we don't need to change that. 

I modified the lets encrypt config file for snap-cloud.cs10.org to use snapCloud/certs/snap-cloud.CS10.org as the directory to store cert files. (This is `/etc/letsencrypt/renewal/snap-cloud.CS10.org.conf`)

I then added a script to `/etc/letsencrypt/renewal-hooks/deploy/1-restart-lapis.sh`. It will simply call the daemon to restart the server. It will only run when the cert renewal is successful. 

## TODO
- [ ] repeat this process for the staging server
- [ ] make copies of lets encrypt config files in the repo
- [ ] have a setup script that puts the config files in the proper locations
- [ ] have the setup script create the deploy hook

**Comment by bromagosa** [comment]
Hmm this autoclosed itself, sorry.

**Comment by cycomachead** [comment]
I used the word “fix”. But GitHub doesn’t know how to treat “partial fix”. :)

-- 
Michael Ball
From my iPhone
michaelball.co
